// Trail data types and curated trail information for National Parks
// Separated from national-parks-data.ts to avoid bloating that file

import { nationalParks } from './national-parks-data';

export type TrailDifficulty = 'easy' | 'moderate' | 'strenuous';

export interface Trail {
  id: string;
  name: string;
  distance: number; // miles (round-trip unless noted)
  difficulty: TrailDifficulty;
  elevationGain?: number; // feet
  description: string;
  trailhead: [number, number]; // [lng, lat]
  isLoop?: boolean;
  photoUrl?: string; // Scenic trail photo URL (NPS or Unsplash) - optional override
  photoCredit?: string; // Attribution for the photo source
}

export interface ParkTrails {
  parkId: string;
  trails: Trail[];
}

// Image resolution result
export interface TrailImage {
  url: string;
  credit: string;
}

// Difficulty color mapping for UI
export const DIFFICULTY_COLORS: Record<TrailDifficulty, { bg: string; text: string; border: string }> = {
  easy: { bg: 'bg-emerald-100', text: 'text-emerald-800', border: 'border-emerald-200' },
  moderate: { bg: 'bg-amber-100', text: 'text-amber-800', border: 'border-amber-200' },
  strenuous: { bg: 'bg-red-100', text: 'text-red-800', border: 'border-red-200' },
};

// Get trail image with fallback to park hero image
export function getTrailImage(trail: Trail, parkId: string): TrailImage | null {
  // Prefer trail-specific image if available
  if (trail.photoUrl) {
    return { url: trail.photoUrl, credit: trail.photoCredit || 'Unsplash' };
  }
  
  // Fall back to park hero image
  const park = nationalParks.find(p => p.id === parkId);
  if (park?.heroImageUrl) {
    return { url: park.heroImageUrl, credit: park.heroImageCredit };
  }
  
  return null;
}

// Helper to look up a trail by its ID across all parks
export function getTrailById(trailId: string): (Trail & { parkId: string }) | null {
  for (const [parkId, trails] of Object.entries(PARK_TRAILS)) {
    const trail = trails.find(t => t.id === trailId);
    if (trail) {
      return { ...trail, parkId };
    }
  }
  return null;
}

// Curated featured trails for popular National Parks
// Data sourced from NPS.gov and AllTrails
export const PARK_TRAILS: Record<string, Trail[]> = {
  // Joshua Tree National Park
  'joshua-tree': [
    {
      id: 'ryan-mountain',
      name: 'Ryan Mountain Trail',
      distance: 3.0,
      difficulty: 'strenuous',
      elevationGain: 1050,
      description: '360-degree panoramic views from the summit. One of the park\'s most rewarding hikes.',
      trailhead: [-116.1369, 33.9856],
    },
    {
      id: 'hidden-valley',
      name: 'Hidden Valley Nature Trail',
      distance: 1.0,
      difficulty: 'easy',
      description: 'Loop through massive boulder formations. Great for rock scrambling and wildlife.',
      trailhead: [-116.1675, 34.0117],
      isLoop: true,
    },
    {
      id: 'barker-dam',
      name: 'Barker Dam Loop',
      distance: 1.1,
      difficulty: 'easy',
      description: 'Historic dam and Native American petroglyphs. Best after rain when the dam holds water.',
      trailhead: [-116.1585, 34.0203],
      isLoop: true,
    },
    {
      id: 'skull-rock',
      name: 'Skull Rock Nature Trail',
      distance: 1.7,
      difficulty: 'easy',
      description: 'Iconic skull-shaped boulder and desert wash exploration.',
      trailhead: [-116.0544, 34.0024],
      isLoop: true,
    },
    {
      id: 'lost-horse-mine',
      name: 'Lost Horse Mine Trail',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 480,
      description: 'Historic gold mining ruins with expansive desert views.',
      trailhead: [-116.1553, 33.9667],
    },
    {
      id: 'fortynine-palms-oasis',
      name: '49 Palms Oasis Trail',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Desert oasis with fan palms. Best in cooler months.',
      trailhead: [-116.1028, 34.1067],
    },
  ],

  // Grand Canyon National Park
  'grand-canyon': [
    {
      id: 'bright-angel',
      name: 'Bright Angel Trail',
      distance: 12.4,
      difficulty: 'strenuous',
      elevationGain: 4380,
      description: 'Iconic rim-to-river trail. Day hikers should turn around at 1.5 or 3-Mile Resthouse.',
      trailhead: [-112.1435, 36.0576],
    },
    {
      id: 'south-kaibab',
      name: 'South Kaibab Trail',
      distance: 6.4,
      difficulty: 'strenuous',
      elevationGain: 4860,
      description: 'Steep descent with panoramic views. No water - carry plenty. Ooh Aah Point is a popular turnaround.',
      trailhead: [-112.0837, 36.0531],
    },
    {
      id: 'rim-trail',
      name: 'Rim Trail',
      distance: 13.0,
      difficulty: 'easy',
      description: 'Paved and flat. Walk any section for stunning canyon views. Connects major viewpoints.',
      trailhead: [-112.1397, 36.0571],
    },
    {
      id: 'hermit-trail',
      name: 'Hermit Trail',
      distance: 18.8,
      difficulty: 'strenuous',
      elevationGain: 5200,
      description: 'Less crowded wilderness trail. Rocky and unmaintained below Santa Maria Spring.',
      trailhead: [-112.2078, 36.0642],
    },
  ],

  // Yosemite National Park
  'yosemite': [
    {
      id: 'half-dome',
      name: 'Half Dome',
      distance: 16.0,
      difficulty: 'strenuous',
      elevationGain: 4800,
      description: 'Iconic granite dome. Permit required for cables. Start before dawn.',
      trailhead: [-119.5584, 37.7270],
    },
    {
      id: 'mist-trail',
      name: 'Mist Trail to Vernal Fall',
      distance: 5.4,
      difficulty: 'strenuous',
      elevationGain: 1000,
      description: 'Get soaked by Vernal Fall spray. Continue to Nevada Fall for the full experience.',
      trailhead: [-119.5584, 37.7270],
    },
    {
      id: 'yosemite-falls',
      name: 'Yosemite Falls Trail',
      distance: 7.2,
      difficulty: 'strenuous',
      elevationGain: 2700,
      description: 'Climb to top of North America\'s tallest waterfall. Best in spring.',
      trailhead: [-119.5972, 37.7457],
    },
    {
      id: 'valley-loop',
      name: 'Valley Loop Trail',
      distance: 11.5,
      difficulty: 'easy',
      description: 'Flat loop around Yosemite Valley floor. Views of El Capitan and Bridalveil Fall.',
      trailhead: [-119.5912, 37.7416],
      isLoop: true,
    },
    {
      id: 'mirror-lake',
      name: 'Mirror Lake Loop',
      distance: 5.0,
      difficulty: 'easy',
      description: 'Reflections of Half Dome and Mt. Watkins. Best in spring when lake is full.',
      trailhead: [-119.5559, 37.7442],
      isLoop: true,
    },
  ],

  // Zion National Park
  'zion': [
    {
      id: 'angels-landing',
      name: 'Angels Landing',
      distance: 5.4,
      difficulty: 'strenuous',
      elevationGain: 1488,
      description: 'Thrilling knife-edge ridge with chains. Permit required. Not for those afraid of heights.',
      trailhead: [-112.9508, 37.2592],
    },
    {
      id: 'the-narrows',
      name: 'The Narrows (Bottom-Up)',
      distance: 9.0,
      difficulty: 'strenuous',
      description: 'Wade through the Virgin River between 2000ft canyon walls. Rent gear in Springdale.',
      trailhead: [-112.9469, 37.2850],
    },
    {
      id: 'observation-point',
      name: 'Observation Point',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 2148,
      description: 'Highest viewpoint in Zion Canyon. Look down on Angels Landing.',
      trailhead: [-112.9380, 37.2693],
    },
    {
      id: 'riverside-walk',
      name: 'Riverside Walk',
      distance: 2.2,
      difficulty: 'easy',
      description: 'Paved path to the start of The Narrows. Hanging gardens and canyon views.',
      trailhead: [-112.9469, 37.2850],
    },
    {
      id: 'emerald-pools',
      name: 'Emerald Pools Trail',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 350,
      description: 'Three tiered pools with seasonal waterfalls. Lower pool is wheelchair accessible.',
      trailhead: [-112.9578, 37.2553],
    },
  ],

  // Yellowstone National Park
  'yellowstone': [
    {
      id: 'old-faithful-geyser',
      name: 'Old Faithful Geyser Loop',
      distance: 1.0,
      difficulty: 'easy',
      description: 'Boardwalk loop around Old Faithful and nearby thermal features.',
      trailhead: [-110.8282, 44.4605],
      isLoop: true,
    },
    {
      id: 'grand-prismatic',
      name: 'Grand Prismatic Overlook',
      distance: 1.6,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Best view of the famous rainbow hot spring. Short but steep.',
      trailhead: [-110.8381, 44.5247],
    },
    {
      id: 'uncle-tom-trail',
      name: 'Uncle Tom\'s Trail',
      distance: 0.5,
      difficulty: 'moderate',
      elevationGain: 500,
      description: '328 steel stairs to Lower Yellowstone Falls. Strenuous on the return.',
      trailhead: [-110.4950, 44.7180],
    },
    {
      id: 'mt-washburn',
      name: 'Mount Washburn',
      distance: 6.4,
      difficulty: 'moderate',
      elevationGain: 1400,
      description: 'Fire lookout with 360-degree views. Watch for bighorn sheep.',
      trailhead: [-110.4372, 44.7985],
    },
    {
      id: 'fairy-falls',
      name: 'Fairy Falls',
      distance: 5.4,
      difficulty: 'easy',
      description: '197-foot waterfall plus Grand Prismatic overlook on the way.',
      trailhead: [-110.8548, 44.5247],
    },
  ],

  // Rocky Mountain National Park
  'rocky-mountain': [
    {
      id: 'sky-pond',
      name: 'Sky Pond',
      distance: 9.8,
      difficulty: 'strenuous',
      elevationGain: 1740,
      description: 'Alpine lake beneath the Cathedral Spires. Scramble up The Loch and Timberline Falls.',
      trailhead: [-105.6421, 40.3117],
    },
    {
      id: 'bear-lake',
      name: 'Bear Lake Loop',
      distance: 0.8,
      difficulty: 'easy',
      description: 'Scenic alpine lake with mountain reflections. Fully accessible.',
      trailhead: [-105.6456, 40.3117],
      isLoop: true,
    },
    {
      id: 'emerald-lake-romo',
      name: 'Emerald Lake Trail',
      distance: 3.6,
      difficulty: 'moderate',
      elevationGain: 650,
      description: 'Three alpine lakes: Nymph, Dream, and Emerald. One of the park\'s most popular.',
      trailhead: [-105.6456, 40.3117],
    },
    {
      id: 'chasm-lake',
      name: 'Chasm Lake',
      distance: 8.4,
      difficulty: 'strenuous',
      elevationGain: 2360,
      description: 'Dramatic lake beneath Longs Peak\'s Diamond face. High altitude challenge.',
      trailhead: [-105.5572, 40.2705],
    },
    {
      id: 'alberta-falls',
      name: 'Alberta Falls',
      distance: 1.6,
      difficulty: 'easy',
      elevationGain: 200,
      description: '30-foot waterfall through Glacier Gorge. Great for families.',
      trailhead: [-105.6380, 40.3106],
    },
  ],

  // Acadia National Park
  'acadia': [
    {
      id: 'precipice',
      name: 'Precipice Trail',
      distance: 1.6,
      difficulty: 'strenuous',
      elevationGain: 1000,
      description: 'Iron rungs and ladders up cliff face. Closed during peregrine falcon nesting.',
      trailhead: [-68.1889, 44.3489],
    },
    {
      id: 'beehive',
      name: 'Beehive Loop',
      distance: 1.5,
      difficulty: 'strenuous',
      elevationGain: 450,
      description: 'Iron rungs up exposed granite with Sand Beach views. Thrilling but not for everyone.',
      trailhead: [-68.1856, 44.3306],
    },
    {
      id: 'cadillac-summit',
      name: 'Cadillac Summit Loop',
      distance: 0.5,
      difficulty: 'easy',
      description: 'First place to see sunrise in the US (Oct-Mar). Paved summit loop.',
      trailhead: [-68.2253, 44.3522],
      isLoop: true,
    },
    {
      id: 'jordan-pond',
      name: 'Jordan Pond Path',
      distance: 3.3,
      difficulty: 'easy',
      description: 'Loop around crystal-clear pond with North Bubble views. Pop into Jordan Pond House for popovers.',
      trailhead: [-68.2531, 44.3206],
      isLoop: true,
    },
    {
      id: 'bubble-rock',
      name: 'South Bubble',
      distance: 1.0,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Glacial erratic "Bubble Rock" balanced on cliff edge.',
      trailhead: [-68.2514, 44.3286],
    },
  ],

  // Grand Teton National Park
  'grand-teton': [
    {
      id: 'cascade-canyon',
      name: 'Cascade Canyon',
      distance: 9.1,
      difficulty: 'moderate',
      elevationGain: 1100,
      description: 'Take the Jenny Lake boat shuttle to cut 4 miles. Watch for moose.',
      trailhead: [-110.7261, 43.7706],
    },
    {
      id: 'delta-lake',
      name: 'Delta Lake',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 2300,
      description: 'Turquoise glacial lake beneath the Grand. Unmarked but well-worn social trail.',
      trailhead: [-110.6850, 43.7583],
    },
    {
      id: 'taggart-lake',
      name: 'Taggart Lake',
      distance: 3.0,
      difficulty: 'easy',
      elevationGain: 350,
      description: 'Picturesque lake with Teton backdrop. Great for families.',
      trailhead: [-110.7330, 43.7020],
    },
    {
      id: 'lake-solitude',
      name: 'Lake Solitude',
      distance: 14.5,
      difficulty: 'strenuous',
      elevationGain: 2400,
      description: 'Remote alpine lake at canyon\'s head. All-day adventure.',
      trailhead: [-110.7261, 43.7706],
    },
    {
      id: 'inspiration-point',
      name: 'Inspiration Point',
      distance: 2.0,
      difficulty: 'moderate',
      elevationGain: 420,
      description: 'Jenny Lake overlook via shuttle. Combine with Hidden Falls.',
      trailhead: [-110.7261, 43.7706],
    },
  ],

  // Glacier National Park
  'glacier': [
    {
      id: 'highline',
      name: 'Highline Trail',
      distance: 11.8,
      difficulty: 'strenuous',
      elevationGain: 830,
      description: 'Continental Divide traverse from Logan Pass. Arrange shuttle or hitchhike back.',
      trailhead: [-113.7187, 48.6964],
    },
    {
      id: 'grinnell-glacier',
      name: 'Grinnell Glacier',
      distance: 10.6,
      difficulty: 'strenuous',
      elevationGain: 1600,
      description: 'Hike to one of the park\'s remaining glaciers. Take boat shuttle to save 4 miles.',
      trailhead: [-113.6548, 48.7974],
    },
    {
      id: 'avalanche-lake',
      name: 'Avalanche Lake',
      distance: 5.9,
      difficulty: 'moderate',
      elevationGain: 730,
      description: 'Through old-growth cedar forest to glacial cirque. One of the park\'s most popular.',
      trailhead: [-113.8189, 48.6817],
    },
    {
      id: 'hidden-lake',
      name: 'Hidden Lake Overlook',
      distance: 2.7,
      difficulty: 'moderate',
      elevationGain: 540,
      description: 'Boardwalk from Logan Pass through alpine meadows. Mountain goats common.',
      trailhead: [-113.7187, 48.6964],
    },
    {
      id: 'iceberg-lake',
      name: 'Iceberg Lake',
      distance: 9.7,
      difficulty: 'moderate',
      elevationGain: 1200,
      description: 'Lake with floating icebergs into summer. Spectacular cirque walls.',
      trailhead: [-113.6789, 48.7970],
    },
  ],

  // Great Smoky Mountains National Park
  'great-smoky-mountains': [
    {
      id: 'alum-cave',
      name: 'Alum Cave Trail to Mt. LeConte',
      distance: 11.0,
      difficulty: 'strenuous',
      elevationGain: 2763,
      description: 'Most popular route to LeConte Lodge. Spectacular arch and cliff faces.',
      trailhead: [-83.4511, 35.6308],
    },
    {
      id: 'chimney-tops',
      name: 'Chimney Tops',
      distance: 4.0,
      difficulty: 'strenuous',
      elevationGain: 1400,
      description: 'Steep climb to rocky pinnacle. Trail damaged by 2016 fires but reopened.',
      trailhead: [-83.4728, 35.6281],
    },
    {
      id: 'laurel-falls',
      name: 'Laurel Falls',
      distance: 2.6,
      difficulty: 'easy',
      description: '80-foot waterfall on paved trail. Very popular - go early.',
      trailhead: [-83.6117, 35.6700],
    },
    {
      id: 'abrams-falls',
      name: 'Abrams Falls',
      distance: 5.0,
      difficulty: 'moderate',
      elevationGain: 650,
      description: '20-foot wide falls in Cades Cove area. Swimming is dangerous.',
      trailhead: [-83.8450, 35.6042],
    },
    {
      id: 'rainbow-falls',
      name: 'Rainbow Falls',
      distance: 5.4,
      difficulty: 'moderate',
      elevationGain: 1685,
      description: '80-foot falls that create rainbows on sunny afternoons.',
      trailhead: [-83.4953, 35.6736],
    },
  ],

  // Death Valley National Park
  'death-valley': [
    {
      id: 'badwater-salt-flat',
      name: 'Badwater Basin Salt Flat',
      distance: 2.0,
      difficulty: 'easy',
      description: 'Walk on the lowest point in North America at 282 feet below sea level.',
      trailhead: [-116.8325, 36.2296],
    },
    {
      id: 'golden-canyon',
      name: 'Golden Canyon to Red Cathedral',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 800,
      description: 'Colorful canyon walls lead to dramatic red cliffs. Best in morning light.',
      trailhead: [-116.8470, 36.4206],
    },
    {
      id: 'mosaic-canyon',
      name: 'Mosaic Canyon',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 300,
      description: 'Polished marble narrows and mosaic breccia walls. Slot canyon feel.',
      trailhead: [-117.1467, 36.5703],
    },
    {
      id: 'telescope-peak',
      name: 'Telescope Peak',
      distance: 14.0,
      difficulty: 'strenuous',
      elevationGain: 3000,
      description: 'Highest point in the park at 11,049 ft. Views from Badwater to Mt. Whitney.',
      trailhead: [-117.0808, 36.1694],
    },
    {
      id: 'natural-bridge',
      name: 'Natural Bridge Canyon',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 400,
      description: 'Short canyon hike to a 35-foot natural rock bridge and dry waterfall.',
      trailhead: [-116.7806, 36.3472],
    },
    {
      id: 'mesquite-dunes',
      name: 'Mesquite Flat Sand Dunes',
      distance: 2.0,
      difficulty: 'moderate',
      description: 'Tallest dunes in the park at 100 feet. Best at sunrise or sunset.',
      trailhead: [-117.1161, 36.6117],
    },
  ],

  // Arches National Park
  'arches': [
    {
      id: 'delicate-arch',
      name: 'Delicate Arch',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 480,
      description: 'Utah\'s most iconic arch. Timed entry required. Stunning at sunset.',
      trailhead: [-109.5208, 38.7356],
    },
    {
      id: 'devils-garden',
      name: 'Devils Garden Loop',
      distance: 7.9,
      difficulty: 'strenuous',
      elevationGain: 800,
      description: 'Eight arches including 306-foot Landscape Arch. Primitive trail adds adventure.',
      trailhead: [-109.5947, 38.7828],
      isLoop: true,
    },
    {
      id: 'park-avenue',
      name: 'Park Avenue',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 320,
      description: 'Walk between towering sandstone skyscrapers. One-way with shuttle.',
      trailhead: [-109.5950, 38.6183],
    },
    {
      id: 'double-arch',
      name: 'Double Arch',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Two massive arches sharing the same foundation. Easy and impressive.',
      trailhead: [-109.5367, 38.6878],
    },
    {
      id: 'landscape-arch',
      name: 'Landscape Arch',
      distance: 1.6,
      difficulty: 'easy',
      description: 'One of the longest natural arches in the world at 306 feet span.',
      trailhead: [-109.5947, 38.7828],
    },
    {
      id: 'broken-arch',
      name: 'Broken Arch Loop',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Through grassland to a freestanding arch. Less crowded alternative.',
      trailhead: [-109.5850, 38.7561],
      isLoop: true,
    },
  ],

  // Bryce Canyon National Park
  'bryce-canyon': [
    {
      id: 'queens-garden-navajo',
      name: 'Queens Garden + Navajo Loop',
      distance: 2.9,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Best hoodoo combo trail. Descend through Wall Street, return via Queens Garden.',
      trailhead: [-112.1672, 37.6231],
    },
    {
      id: 'fairyland-loop',
      name: 'Fairyland Loop',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 1500,
      description: 'Less crowded hoodoo wonderland. Tower Bridge and China Wall formations.',
      trailhead: [-112.1569, 37.6483],
      isLoop: true,
    },
    {
      id: 'rim-trail-bryce',
      name: 'Rim Trail',
      distance: 11.0,
      difficulty: 'easy',
      elevationGain: 500,
      description: 'Connects all major viewpoints. Walk any section for stunning views.',
      trailhead: [-112.1606, 37.6289],
    },
    {
      id: 'peek-a-boo-loop',
      name: 'Peek-A-Boo Loop',
      distance: 5.5,
      difficulty: 'strenuous',
      elevationGain: 1500,
      description: 'Through the heart of the amphitheater. Wall of Windows highlight.',
      trailhead: [-112.1631, 37.6189],
      isLoop: true,
    },
    {
      id: 'tower-bridge',
      name: 'Tower Bridge',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 800,
      description: 'Natural bridge formation via Fairyland Trail. Quieter side of the park.',
      trailhead: [-112.1569, 37.6483],
    },
    {
      id: 'mossy-cave',
      name: 'Mossy Cave',
      distance: 0.8,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Small waterfall and ice cave. Off the beaten path near Highway 12.',
      trailhead: [-112.0817, 37.6422],
    },
  ],

  // Olympic National Park
  'olympic': [
    {
      id: 'hoh-rain-forest',
      name: 'Hall of Mosses',
      distance: 1.1,
      difficulty: 'easy',
      description: 'Iconic temperate rainforest loop. Moss-draped maples and giant ferns.',
      trailhead: [-123.9328, 47.8608],
      isLoop: true,
    },
    {
      id: 'hurricane-hill',
      name: 'Hurricane Hill',
      distance: 3.2,
      difficulty: 'moderate',
      elevationGain: 650,
      description: 'Alpine meadows with views of Mt. Olympus and Strait of Juan de Fuca.',
      trailhead: [-123.4989, 47.9742],
    },
    {
      id: 'sol-duc-falls',
      name: 'Sol Duc Falls',
      distance: 1.6,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Stunning three-pronged waterfall through old-growth forest.',
      trailhead: [-123.8364, 47.9553],
    },
    {
      id: 'rialto-beach',
      name: 'Rialto Beach to Hole-in-the-Wall',
      distance: 4.0,
      difficulty: 'moderate',
      description: 'Coastal walk past sea stacks to natural arch. Check tide tables.',
      trailhead: [-124.6378, 47.9206],
    },
    {
      id: 'mount-storm-king',
      name: 'Mount Storm King',
      distance: 4.0,
      difficulty: 'strenuous',
      elevationGain: 2000,
      description: 'Steep scramble with ropes to Lake Crescent views. Not for acrophobes.',
      trailhead: [-123.7989, 48.0569],
    },
    {
      id: 'marymere-falls',
      name: 'Marymere Falls',
      distance: 1.8,
      difficulty: 'easy',
      elevationGain: 400,
      description: '90-foot waterfall through old-growth. Combine with Storm King.',
      trailhead: [-123.7989, 48.0569],
    },
  ],

  // Shenandoah National Park
  'shenandoah': [
    {
      id: 'old-rag',
      name: 'Old Rag Mountain',
      distance: 9.0,
      difficulty: 'strenuous',
      elevationGain: 2380,
      description: 'Iconic granite rock scramble. Permit required. Start early.',
      trailhead: [-78.2947, 38.5531],
    },
    {
      id: 'dark-hollow-falls',
      name: 'Dark Hollow Falls',
      distance: 1.4,
      difficulty: 'moderate',
      elevationGain: 440,
      description: 'Closest waterfall to Skyline Drive. Short but steep return.',
      trailhead: [-78.4294, 38.5208],
    },
    {
      id: 'whiteoak-canyon',
      name: 'Whiteoak Canyon',
      distance: 4.6,
      difficulty: 'moderate',
      elevationGain: 1000,
      description: 'Six waterfalls in one hike. Tallest at 86 feet. Combine with Cedar Run.',
      trailhead: [-78.3789, 38.5469],
    },
    {
      id: 'hawksbill-summit',
      name: 'Hawksbill Summit',
      distance: 2.9,
      difficulty: 'moderate',
      elevationGain: 860,
      description: 'Highest point in the park at 4,051 feet. Observation platform.',
      trailhead: [-78.3869, 38.5553],
    },
    {
      id: 'bearfence-mountain',
      name: 'Bearfence Mountain',
      distance: 1.2,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Short rock scramble to 360-degree views. Fun and challenging.',
      trailhead: [-78.4653, 38.4583],
    },
    {
      id: 'stony-man',
      name: 'Stony Man',
      distance: 1.6,
      difficulty: 'easy',
      elevationGain: 340,
      description: 'Easy summit with panoramic Shenandoah Valley views. Family-friendly.',
      trailhead: [-78.3722, 38.5944],
    },
  ],

  // Mount Rainier National Park
  'mount-rainier': [
    {
      id: 'skyline-loop',
      name: 'Skyline Loop',
      distance: 5.5,
      difficulty: 'moderate',
      elevationGain: 1700,
      description: 'Paradise\'s premier trail. Wildflower meadows and glacier views.',
      trailhead: [-121.7356, 46.7867],
      isLoop: true,
    },
    {
      id: 'spray-park',
      name: 'Spray Park',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 2000,
      description: 'Less crowded alpine meadows with stunning Rainier views.',
      trailhead: [-121.8644, 46.9136],
    },
    {
      id: 'burroughs-mountain',
      name: 'Burroughs Mountain',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 1900,
      description: 'Walk on ancient volcanic ash. Closest trail to Emmons Glacier.',
      trailhead: [-121.6406, 46.9147],
    },
    {
      id: 'naches-peak-loop',
      name: 'Naches Peak Loop',
      distance: 3.5,
      difficulty: 'easy',
      elevationGain: 500,
      description: 'Wildflowers and Rainier views near Chinook Pass.',
      trailhead: [-121.5175, 46.8683],
      isLoop: true,
    },
    {
      id: 'comet-falls',
      name: 'Comet Falls',
      distance: 3.8,
      difficulty: 'moderate',
      elevationGain: 1300,
      description: '320-foot waterfall through old-growth. One of the park\'s best.',
      trailhead: [-121.7781, 46.7778],
    },
    {
      id: 'tolmie-peak',
      name: 'Tolmie Peak',
      distance: 6.5,
      difficulty: 'moderate',
      elevationGain: 1020,
      description: 'Historic fire lookout with Eunice Lake and Rainier views.',
      trailhead: [-121.8783, 46.9272],
    },
  ],

  // Sequoia National Park
  'sequoia': [
    {
      id: 'general-sherman',
      name: 'General Sherman Tree',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Largest living tree by volume. Paved but steep return.',
      trailhead: [-118.7547, 36.5819],
    },
    {
      id: 'congress-trail',
      name: 'Congress Trail',
      distance: 2.0,
      difficulty: 'easy',
      description: 'Loop through Giant Forest with named sequoias.',
      trailhead: [-118.7547, 36.5819],
      isLoop: true,
    },
    {
      id: 'moro-rock',
      name: 'Moro Rock',
      distance: 0.5,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Climb 350 steps to granite dome with Sierra views.',
      trailhead: [-118.7656, 36.5456],
    },
    {
      id: 'tokopah-falls',
      name: 'Tokopah Falls',
      distance: 3.4,
      difficulty: 'easy',
      elevationGain: 500,
      description: '1,200-foot cascading waterfall. Best in spring.',
      trailhead: [-118.7328, 36.5978],
    },
    {
      id: 'alta-peak',
      name: 'Alta Peak',
      distance: 13.8,
      difficulty: 'strenuous',
      elevationGain: 4000,
      description: 'Panoramic Sierra views from 11,204 ft summit.',
      trailhead: [-118.7422, 36.5922],
    },
    {
      id: 'big-trees',
      name: 'Big Trees Trail',
      distance: 1.3,
      difficulty: 'easy',
      description: 'Accessible boardwalk around Round Meadow.',
      trailhead: [-118.7539, 36.5642],
      isLoop: true,
    },
  ],

  // Cuyahoga Valley National Park
  'cuyahoga-valley': [
    {
      id: 'brandywine-falls',
      name: 'Brandywine Falls',
      distance: 1.5,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Boardwalk to 65-foot waterfall. Most visited spot in the park.',
      trailhead: [-81.5350, 41.2756],
    },
    {
      id: 'blue-hen-falls',
      name: 'Blue Hen Falls',
      distance: 0.6,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Small but photogenic waterfall in secluded gorge.',
      trailhead: [-81.5317, 41.2625],
    },
    {
      id: 'ledges-trail',
      name: 'Ledges Trail',
      distance: 2.2,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Through sandstone formations with Ice Box Cave.',
      trailhead: [-81.5572, 41.2286],
      isLoop: true,
    },
    {
      id: 'towpath-trail',
      name: 'Ohio & Erie Canal Towpath',
      distance: 20.0,
      difficulty: 'easy',
      description: 'Historic canal towpath. Bike or walk any section.',
      trailhead: [-81.5756, 41.2561],
    },
    {
      id: 'stanford-trail',
      name: 'Stanford Trail',
      distance: 1.2,
      difficulty: 'easy',
      description: 'Through forest to Brandywine Falls from the south.',
      trailhead: [-81.5378, 41.2708],
    },
    {
      id: 'buckeye-trail',
      name: 'Buckeye Trail',
      distance: 3.5,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Part of statewide trail system through the valley.',
      trailhead: [-81.5639, 41.2178],
    },
  ],

  // Badlands National Park
  'badlands': [
    {
      id: 'notch-trail',
      name: 'Notch Trail',
      distance: 1.5,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Climb a log ladder to a dramatic canyon overlook.',
      trailhead: [-102.3494, 43.7506],
    },
    {
      id: 'door-trail',
      name: 'Door Trail',
      distance: 0.75,
      difficulty: 'easy',
      description: 'Through a natural door in the Badlands Wall.',
      trailhead: [-102.3964, 43.7508],
    },
    {
      id: 'castle-trail',
      name: 'Castle Trail',
      distance: 10.0,
      difficulty: 'moderate',
      description: 'Longest trail in park through castle-like formations.',
      trailhead: [-102.3494, 43.7506],
    },
    {
      id: 'saddle-pass',
      name: 'Saddle Pass Trail',
      distance: 0.25,
      difficulty: 'strenuous',
      elevationGain: 200,
      description: 'Steep climb up Badlands Wall. Short but challenging.',
      trailhead: [-102.3400, 43.7489],
    },
    {
      id: 'fossil-exhibit',
      name: 'Fossil Exhibit Trail',
      distance: 0.25,
      difficulty: 'easy',
      description: 'Accessible trail with fossil replicas and interpretive signs.',
      trailhead: [-102.3889, 43.7539],
    },
    {
      id: 'cliff-shelf',
      name: 'Cliff Shelf Nature Trail',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Boardwalk loop with juniper forest and views.',
      trailhead: [-102.3578, 43.7556],
      isLoop: true,
    },
  ],

  // Big Bend National Park
  'big-bend': [
    {
      id: 'santa-elena-canyon',
      name: 'Santa Elena Canyon',
      distance: 1.7,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Cross creek and climb stairs into 1,500-foot canyon.',
      trailhead: [-103.6097, 29.1678],
    },
    {
      id: 'lost-mine-trail',
      name: 'Lost Mine Trail',
      distance: 4.8,
      difficulty: 'moderate',
      elevationGain: 1100,
      description: 'Best day hike in Chisos Basin. Stunning views.',
      trailhead: [-103.3019, 29.2744],
    },
    {
      id: 'south-rim-loop',
      name: 'South Rim Loop',
      distance: 13.5,
      difficulty: 'strenuous',
      elevationGain: 2500,
      description: 'Full-day epic through the high Chisos.',
      trailhead: [-103.3019, 29.2700],
      isLoop: true,
    },
    {
      id: 'window-trail',
      name: 'Window Trail',
      distance: 5.6,
      difficulty: 'moderate',
      elevationGain: 800,
      description: 'Descend to pour-off waterfall (seasonal).',
      trailhead: [-103.3017, 29.2700],
    },
    {
      id: 'boquillas-canyon',
      name: 'Boquillas Canyon',
      distance: 1.4,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Riverside walk into dramatic canyon.',
      trailhead: [-102.9475, 29.1975],
    },
    {
      id: 'emory-peak',
      name: 'Emory Peak',
      distance: 10.5,
      difficulty: 'strenuous',
      elevationGain: 2400,
      description: 'Highest point in the park at 7,825 feet.',
      trailhead: [-103.3019, 29.2700],
    },
  ],

  // Lassen Volcanic National Park
  'lassen-volcanic': [
    {
      id: 'lassen-peak',
      name: 'Lassen Peak',
      distance: 5.0,
      difficulty: 'strenuous',
      elevationGain: 2000,
      description: 'Summit active volcano. Thin air at 10,457 feet.',
      trailhead: [-121.5086, 40.4839],
    },
    {
      id: 'bumpass-hell',
      name: 'Bumpass Hell',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 350,
      description: 'Largest hydrothermal area in the park. Boardwalk required.',
      trailhead: [-121.5056, 40.4611],
    },
    {
      id: 'kings-creek-falls',
      name: 'Kings Creek Falls',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 700,
      description: 'Through meadows to cascading waterfall.',
      trailhead: [-121.4703, 40.4581],
    },
    {
      id: 'cinder-cone',
      name: 'Cinder Cone',
      distance: 4.0,
      difficulty: 'strenuous',
      elevationGain: 700,
      description: 'Climb loose volcanic cinders to crater rim.',
      trailhead: [-121.3206, 40.5489],
    },
    {
      id: 'manzanita-lake',
      name: 'Manzanita Lake Loop',
      distance: 1.8,
      difficulty: 'easy',
      description: 'Lakeside stroll with Lassen Peak reflections.',
      trailhead: [-121.5683, 40.5347],
      isLoop: true,
    },
    {
      id: 'terrace-lake',
      name: 'Terrace, Shadow, and Cliff Lakes',
      distance: 3.4,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Three alpine lakes in one scenic loop.',
      trailhead: [-121.4847, 40.4572],
    },
  ],

  // Crater Lake National Park
  'crater-lake': [
    {
      id: 'cleetwood-cove',
      name: 'Cleetwood Cove',
      distance: 2.2,
      difficulty: 'strenuous',
      elevationGain: 700,
      description: 'Only access to lake shore. Boat tour departs here.',
      trailhead: [-122.0847, 42.9797],
    },
    {
      id: 'watchman-peak',
      name: 'Watchman Peak',
      distance: 1.6,
      difficulty: 'moderate',
      elevationGain: 420,
      description: 'Fire lookout with Wizard Island views.',
      trailhead: [-122.1714, 42.9447],
    },
    {
      id: 'garfield-peak',
      name: 'Garfield Peak',
      distance: 3.4,
      difficulty: 'strenuous',
      elevationGain: 1010,
      description: 'Panoramic lake views from 8,054 feet.',
      trailhead: [-122.1350, 42.9131],
    },
    {
      id: 'sun-notch',
      name: 'Sun Notch',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 150,
      description: 'Quick viewpoint of Phantom Ship rock.',
      trailhead: [-122.0861, 42.9017],
    },
    {
      id: 'mount-scott',
      name: 'Mount Scott',
      distance: 5.0,
      difficulty: 'strenuous',
      elevationGain: 1500,
      description: 'Highest point in the park at 8,929 feet.',
      trailhead: [-122.0272, 42.9228],
    },
    {
      id: 'castle-crest-wildflower',
      name: 'Castle Crest Wildflower',
      distance: 0.4,
      difficulty: 'easy',
      description: 'Peak wildflowers in July-August.',
      trailhead: [-122.1214, 42.9072],
      isLoop: true,
    },
  ],

  // Hawaii Volcanoes National Park
  'hawaii-volcanoes': [
    {
      id: 'kilauea-iki',
      name: 'Kilauea Iki Trail',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Descend into 1959 lava lake. Steam vents along crater floor.',
      trailhead: [-155.2450, 19.4147],
    },
    {
      id: 'devastation-trail',
      name: 'Devastation Trail',
      distance: 1.0,
      difficulty: 'easy',
      description: 'Boardwalk through 1959 eruption fallout zone.',
      trailhead: [-155.2414, 19.4178],
    },
    {
      id: 'thurston-lava-tube',
      name: 'Thurston Lava Tube',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Walk through 500-year-old lava tube.',
      trailhead: [-155.2389, 19.4136],
      isLoop: true,
    },
    {
      id: 'halemaumau-overlook',
      name: 'Halemaumau Overlook',
      distance: 1.0,
      difficulty: 'easy',
      description: 'View active lava lake from caldera rim.',
      trailhead: [-155.2567, 19.4028],
    },
    {
      id: 'chain-of-craters',
      name: 'Chain of Craters Road Walk',
      distance: 4.0,
      difficulty: 'moderate',
      description: 'Walk lava fields to sea cliffs. No shade.',
      trailhead: [-155.1139, 19.2931],
    },
    {
      id: 'crater-rim-trail',
      name: 'Crater Rim Trail',
      distance: 11.0,
      difficulty: 'moderate',
      elevationGain: 500,
      description: 'Full caldera circumference. Do sections.',
      trailhead: [-155.2608, 19.4294],
      isLoop: true,
    },
  ],

  // Carlsbad Caverns National Park
  'carlsbad-caverns': [
    {
      id: 'natural-entrance',
      name: 'Natural Entrance Route',
      distance: 1.25,
      difficulty: 'moderate',
      elevationGain: 750,
      description: 'Descend 750 feet through the natural cave mouth.',
      trailhead: [-104.4461, 32.1747],
    },
    {
      id: 'big-room',
      name: 'Big Room Loop',
      distance: 1.25,
      difficulty: 'easy',
      description: 'Largest accessible cave chamber in North America.',
      trailhead: [-104.4461, 32.1747],
      isLoop: true,
    },
    {
      id: 'rattlesnake-canyon',
      name: 'Rattlesnake Canyon',
      distance: 6.0,
      difficulty: 'strenuous',
      elevationGain: 1000,
      description: 'Above-ground desert hike with canyon views.',
      trailhead: [-104.4378, 32.1714],
    },
    {
      id: 'walnut-canyon-desert',
      name: 'Walnut Canyon Desert Drive',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Loop trail near visitor center with desert flora.',
      trailhead: [-104.4461, 32.1747],
    },
    {
      id: 'yucca-canyon',
      name: 'Yucca Canyon Trail',
      distance: 6.0,
      difficulty: 'moderate',
      elevationGain: 800,
      description: 'Backcountry trail through Chihuahuan Desert.',
      trailhead: [-104.4461, 32.1747],
    },
  ],

  // Haleakala National Park
  'haleakala': [
    {
      id: 'sliding-sands',
      name: 'Sliding Sands (Keonehe\'ehe\'e)',
      distance: 11.2,
      difficulty: 'strenuous',
      elevationGain: 2800,
      description: 'Descend into the volcanic crater. Otherworldly landscape.',
      trailhead: [-156.2128, 20.7142],
    },
    {
      id: 'pipiwai',
      name: 'Pipiwai Trail',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 650,
      description: 'Bamboo forest to 400-foot Waimoku Falls.',
      trailhead: [-156.0458, 20.6608],
    },
    {
      id: 'hosmer-grove',
      name: 'Hosmer Grove Nature Trail',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Native and exotic trees. Good for endemic birds.',
      trailhead: [-156.2322, 20.7578],
      isLoop: true,
    },
    {
      id: 'leleiwi-overlook',
      name: 'Leleiwi Overlook Path',
      distance: 0.25,
      difficulty: 'easy',
      description: 'Short walk to crater overlook. Afternoon Brocken spectre.',
      trailhead: [-156.2253, 20.7417],
    },
    {
      id: 'halemau-u',
      name: 'Halemau\'u Trail',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 1400,
      description: 'Switchbacks into crater. Combine with Sliding Sands.',
      trailhead: [-156.2256, 20.7497],
    },
  ],

  // Theodore Roosevelt National Park
  'theodore-roosevelt': [
    {
      id: 'caprock-coulee',
      name: 'Caprock Coulee Nature Trail',
      distance: 0.75,
      difficulty: 'easy',
      description: 'Badlands formations and prairie. Interpretive signs.',
      trailhead: [-103.4258, 47.5922],
      isLoop: true,
    },
    {
      id: 'wind-canyon',
      name: 'Wind Canyon Trail',
      distance: 0.4,
      difficulty: 'easy',
      description: 'Overlook of Little Missouri River. Wind-carved rock.',
      trailhead: [-103.4508, 47.5533],
    },
    {
      id: 'petrified-forest',
      name: 'Petrified Forest Trail',
      distance: 10.0,
      difficulty: 'strenuous',
      elevationGain: 600,
      description: 'Backcountry loop to petrified stumps and logs.',
      trailhead: [-103.4258, 47.5922],
      isLoop: true,
    },
    {
      id: 'buckhorn',
      name: 'Buckhorn Trail',
      distance: 11.0,
      difficulty: 'moderate',
      elevationGain: 550,
      description: 'Prairie dog towns and bison viewing.',
      trailhead: [-103.4003, 47.5861],
      isLoop: true,
    },
    {
      id: 'ridgeline',
      name: 'Ridgeline Nature Trail',
      distance: 0.6,
      difficulty: 'easy',
      description: 'Short loop with panoramic badlands views.',
      trailhead: [-103.5286, 47.5731],
      isLoop: true,
    },
  ],

  // Hot Springs National Park
  'hot-springs': [
    {
      id: 'hot-springs-mountain',
      name: 'Hot Springs Mountain Trail',
      distance: 1.7,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'To observation tower with city and mountain views.',
      trailhead: [-93.0544, 34.5189],
    },
    {
      id: 'west-mountain',
      name: 'West Mountain Trail',
      distance: 1.4,
      difficulty: 'moderate',
      elevationGain: 350,
      description: 'Through forest to West Mountain summit.',
      trailhead: [-93.0586, 34.5139],
    },
    {
      id: 'sunset-trail',
      name: 'Sunset Trail',
      distance: 10.0,
      difficulty: 'strenuous',
      elevationGain: 1200,
      description: 'Longest trail connecting North and West Mountains.',
      trailhead: [-93.0544, 34.5189],
    },
    {
      id: 'grand-promenade',
      name: 'Grand Promenade',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Brick walkway behind historic Bathhouse Row.',
      trailhead: [-93.0531, 34.5136],
    },
    {
      id: 'peak-trail',
      name: 'Peak Trail',
      distance: 0.6,
      difficulty: 'easy',
      elevationGain: 175,
      description: 'Quick climb to Hot Springs Mountain summit.',
      trailhead: [-93.0547, 34.5211],
    },
  ],

  // Mammoth Cave National Park
  'mammoth-cave': [
    {
      id: 'historic-tour',
      name: 'Historic Tour (Cave)',
      distance: 2.0,
      difficulty: 'moderate',
      description: 'Classic cave tour through massive chambers.',
      trailhead: [-86.0997, 37.1869],
    },
    {
      id: 'cedar-sink',
      name: 'Cedar Sink Trail',
      distance: 1.8,
      difficulty: 'moderate',
      elevationGain: 280,
      description: 'Descent into large sinkhole. Above-ground geology.',
      trailhead: [-86.1167, 37.1544],
    },
    {
      id: 'green-river-bluffs',
      name: 'Green River Bluffs Trail',
      distance: 1.1,
      difficulty: 'easy',
      description: 'River overlook and geological features.',
      trailhead: [-86.0997, 37.1869],
    },
    {
      id: 'heritage-trail',
      name: 'Heritage Trail',
      distance: 0.25,
      difficulty: 'easy',
      description: 'Accessible paved path near visitor center.',
      trailhead: [-86.0997, 37.1869],
    },
    {
      id: 'sal-hollow',
      name: 'Sal Hollow Trail',
      distance: 8.2,
      difficulty: 'strenuous',
      elevationGain: 600,
      description: 'Backcountry loop through forest and sinkholes.',
      trailhead: [-86.1078, 37.2036],
      isLoop: true,
    },
  ],

  // Everglades National Park
  'everglades': [
    {
      id: 'anhinga-trail',
      name: 'Anhinga Trail',
      distance: 0.8,
      difficulty: 'easy',
      description: 'Boardwalk with guaranteed alligator sightings.',
      trailhead: [-80.6103, 25.4247],
      isLoop: true,
    },
    {
      id: 'shark-valley',
      name: 'Shark Valley Loop',
      distance: 15.0,
      difficulty: 'moderate',
      description: 'Paved loop with observation tower. Bike or tram option.',
      trailhead: [-80.7653, 25.7589],
      isLoop: true,
    },
    {
      id: 'coastal-prairie',
      name: 'Coastal Prairie Trail',
      distance: 7.5,
      difficulty: 'moderate',
      description: 'Flamingo area trail through prairie to Clubhouse Beach.',
      trailhead: [-80.9256, 25.1417],
    },
    {
      id: 'gumbo-limbo',
      name: 'Gumbo Limbo Trail',
      distance: 0.4,
      difficulty: 'easy',
      description: 'Tropical hardwood hammock. Named for distinctive tree.',
      trailhead: [-80.6103, 25.4247],
      isLoop: true,
    },
    {
      id: 'pa-hay-okee',
      name: 'Pa-hay-okee Overlook',
      distance: 0.16,
      difficulty: 'easy',
      description: 'Short boardwalk to "River of Grass" overlook.',
      trailhead: [-80.7856, 25.4178],
    },
  ],

  // Guadalupe Mountains National Park
  'guadalupe-mountains': [
    {
      id: 'guadalupe-peak',
      name: 'Guadalupe Peak',
      distance: 8.4,
      difficulty: 'strenuous',
      elevationGain: 3000,
      description: 'Highest point in Texas at 8,751 feet.',
      trailhead: [-104.8592, 31.8911],
    },
    {
      id: 'devils-hall',
      name: 'Devil\'s Hall',
      distance: 4.2,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Slot canyon with natural staircase.',
      trailhead: [-104.8592, 31.8911],
    },
    {
      id: 'mckittrick-canyon',
      name: 'McKittrick Canyon',
      distance: 6.8,
      difficulty: 'moderate',
      elevationGain: 700,
      description: 'Best fall colors in Texas. Historic Pratt Cabin.',
      trailhead: [-104.7553, 31.9786],
    },
    {
      id: 'el-capitan',
      name: 'El Capitan Trail',
      distance: 11.3,
      difficulty: 'strenuous',
      elevationGain: 1500,
      description: 'Circles the iconic limestone cliff.',
      trailhead: [-104.8592, 31.8911],
    },
    {
      id: 'smith-spring',
      name: 'Smith Spring Loop',
      distance: 2.3,
      difficulty: 'easy',
      elevationGain: 300,
      description: 'Desert oasis with maidenhair ferns.',
      trailhead: [-104.8236, 31.9247],
      isLoop: true,
    },
  ],

  // Mesa Verde National Park
  'mesa-verde': [
    {
      id: 'petroglyph-point',
      name: 'Petroglyph Point',
      distance: 2.8,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Ancestral Puebloan rock art and canyon views.',
      trailhead: [-108.4869, 37.1833],
      isLoop: true,
    },
    {
      id: 'spruce-canyon',
      name: 'Spruce Canyon Trail',
      distance: 2.4,
      difficulty: 'moderate',
      elevationGain: 500,
      description: 'Descend into canyon below the museum.',
      trailhead: [-108.4869, 37.1833],
      isLoop: true,
    },
    {
      id: 'cliff-palace',
      name: 'Cliff Palace Loop',
      distance: 0.25,
      difficulty: 'moderate',
      description: 'Ranger-led tour of largest cliff dwelling. Ticket required.',
      trailhead: [-108.4731, 37.1678],
    },
    {
      id: 'knife-edge',
      name: 'Knife Edge Trail',
      distance: 2.0,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Montezuma Valley views along old road.',
      trailhead: [-108.4081, 37.2344],
    },
    {
      id: 'soda-canyon',
      name: 'Soda Canyon Overlook',
      distance: 1.2,
      difficulty: 'easy',
      description: 'Views of Balcony House cliff dwelling.',
      trailhead: [-108.4697, 37.1722],
    },
  ],

  // Redwood National Park
  'redwood': [
    {
      id: 'tall-trees-grove',
      name: 'Tall Trees Grove',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 800,
      description: 'Home to some of the tallest trees. Permit required.',
      trailhead: [-123.9917, 41.2097],
    },
    {
      id: 'fern-canyon',
      name: 'Fern Canyon Loop',
      distance: 1.1,
      difficulty: 'easy',
      description: 'Walk through 50-foot walls of ferns. Jurassic Park filming location.',
      trailhead: [-124.0625, 41.4031],
      isLoop: true,
    },
    {
      id: 'lady-bird-johnson',
      name: 'Lady Bird Johnson Grove',
      distance: 1.5,
      difficulty: 'easy',
      description: 'Old-growth redwood loop. Dedication site.',
      trailhead: [-123.9819, 41.3036],
      isLoop: true,
    },
    {
      id: 'boy-scout-tree',
      name: 'Boy Scout Tree Trail',
      distance: 5.6,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Less crowded old-growth to massive twin-trunked redwood.',
      trailhead: [-124.0839, 41.7867],
    },
    {
      id: 'trillium-falls',
      name: 'Trillium Falls',
      distance: 2.5,
      difficulty: 'easy',
      elevationGain: 300,
      description: 'Small waterfall through second-growth forest.',
      trailhead: [-124.0303, 41.4111],
      isLoop: true,
    },
  ],

  // Congaree National Park
  'congaree': [
    {
      id: 'boardwalk-loop',
      name: 'Boardwalk Loop',
      distance: 2.4,
      difficulty: 'easy',
      description: 'Elevated walk through old-growth floodplain forest.',
      trailhead: [-80.7831, 33.7864],
      isLoop: true,
    },
    {
      id: 'weston-lake-loop',
      name: 'Weston Lake Loop',
      distance: 4.4,
      difficulty: 'moderate',
      description: 'Oxbow lake with national champion trees.',
      trailhead: [-80.7831, 33.7864],
      isLoop: true,
    },
    {
      id: 'oakridge-trail',
      name: 'Oakridge Trail',
      distance: 7.5,
      difficulty: 'moderate',
      description: 'Through bluffs and floodplain. May flood.',
      trailhead: [-80.7831, 33.7864],
    },
    {
      id: 'river-trail',
      name: 'River Trail',
      distance: 10.0,
      difficulty: 'strenuous',
      description: 'To Cedar Creek canoe launch. Very remote.',
      trailhead: [-80.7831, 33.7864],
    },
    {
      id: 'bluff-trail',
      name: 'Bluff Trail',
      distance: 0.7,
      difficulty: 'easy',
      description: 'Dry ridge trail connecting loops.',
      trailhead: [-80.7831, 33.7864],
    },
  ],

  // Isle Royale National Park
  'isle-royale': [
    {
      id: 'greenstone-ridge',
      name: 'Greenstone Ridge Trail',
      distance: 42.0,
      difficulty: 'strenuous',
      elevationGain: 4000,
      description: 'End-to-end island traverse. Multi-day backpack.',
      trailhead: [-89.1417, 47.9003],
    },
    {
      id: 'scoville-point',
      name: 'Scoville Point',
      distance: 4.2,
      difficulty: 'easy',
      description: 'Rocky peninsula with harbor views.',
      trailhead: [-88.5511, 48.0992],
      isLoop: true,
    },
    {
      id: 'lookout-louise',
      name: 'Lookout Louise',
      distance: 1.0,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Quick climb to lake overlook.',
      trailhead: [-88.5511, 48.0992],
    },
    {
      id: 'huginnin-cove-loop',
      name: 'Huginnin Cove Loop',
      distance: 9.4,
      difficulty: 'moderate',
      description: 'Remote cove with backcountry camping.',
      trailhead: [-88.5511, 48.0992],
      isLoop: true,
    },
    {
      id: 'stoll-trail',
      name: 'Stoll Trail',
      distance: 4.0,
      difficulty: 'easy',
      description: 'Historic lighthouse and shoreline.',
      trailhead: [-88.5511, 48.0992],
      isLoop: true,
    },
  ],

  // Voyageurs National Park
  'voyageurs': [
    {
      id: 'blind-ash-bay',
      name: 'Blind Ash Bay Trail',
      distance: 2.5,
      difficulty: 'easy',
      description: 'Wetland trail with beaver activity.',
      trailhead: [-93.0556, 48.4978],
    },
    {
      id: 'cruiser-lake-loop',
      name: 'Cruiser Lake Loop',
      distance: 9.5,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Boat access only. Interior lake loop.',
      trailhead: [-93.1000, 48.4500],
      isLoop: true,
    },
    {
      id: 'locator-lake',
      name: 'Locator Lake',
      distance: 4.0,
      difficulty: 'moderate',
      description: 'Remote interior lake. Boat to trailhead.',
      trailhead: [-93.1000, 48.4500],
    },
    {
      id: 'echo-bay',
      name: 'Echo Bay Trail',
      distance: 2.5,
      difficulty: 'easy',
      description: 'Beaver ponds and boreal forest.',
      trailhead: [-93.0800, 48.4600],
    },
    {
      id: 'kabetogama-lake-overlook',
      name: 'Kabetogama Lake Overlook',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Quick hike to lake panorama.',
      trailhead: [-93.0556, 48.4978],
    },
  ],

  // Dry Tortugas National Park
  'dry-tortugas': [
    {
      id: 'fort-jefferson',
      name: 'Fort Jefferson Tour',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Self-guided tour of Civil War-era fort.',
      trailhead: [-82.8732, 24.6285],
      isLoop: true,
    },
    {
      id: 'moat-walk',
      name: 'Moat Walk',
      distance: 0.6,
      difficulty: 'easy',
      description: 'Circumnavigate the fort on the moat wall.',
      trailhead: [-82.8732, 24.6285],
      isLoop: true,
    },
    {
      id: 'beach-walk',
      name: 'Beach Walk',
      distance: 0.4,
      difficulty: 'easy',
      description: 'Sandy beach on Garden Key.',
      trailhead: [-82.8732, 24.6285],
    },
    {
      id: 'bush-key',
      name: 'Bush Key (Seasonal)',
      distance: 0.2,
      difficulty: 'easy',
      description: 'Wade to nearby key. Closed during bird nesting.',
      trailhead: [-82.8700, 24.6300],
    },
    {
      id: 'snorkel-trail',
      name: 'Snorkel Trail',
      distance: 0.3,
      difficulty: 'moderate',
      description: 'Underwater coral viewing near fort.',
      trailhead: [-82.8732, 24.6285],
    },
  ],

  // Biscayne National Park
  'biscayne': [
    {
      id: 'elliott-key-nature',
      name: 'Elliott Key Nature Trail',
      distance: 1.0,
      difficulty: 'easy',
      description: 'Hardwood hammock and mangrove forest.',
      trailhead: [-80.2350, 25.4450],
      isLoop: true,
    },
    {
      id: 'boca-chita-lighthouse',
      name: 'Boca Chita Lighthouse',
      distance: 0.5,
      difficulty: 'easy',
      description: 'Historic lighthouse on small key. Boat access.',
      trailhead: [-80.1750, 25.4700],
      isLoop: true,
    },
    {
      id: 'adams-key-walk',
      name: 'Adams Key Walk',
      distance: 0.3,
      difficulty: 'easy',
      description: 'Former presidential retreat. Boat access only.',
      trailhead: [-80.2350, 25.3950],
    },
    {
      id: 'spite-highway',
      name: 'Spite Highway',
      distance: 7.0,
      difficulty: 'strenuous',
      description: 'Old road through dense vegetation on Elliott Key.',
      trailhead: [-80.2350, 25.4450],
    },
    {
      id: 'underwater-trail',
      name: 'Maritime Heritage Trail',
      distance: 0.5,
      difficulty: 'moderate',
      description: 'Snorkel trail to shipwrecks. Boat access.',
      trailhead: [-80.1800, 25.4000],
    },
  ],

  // ==========================================
  // PHASE 3A: ALASKA PARKS (8 Parks)
  // ==========================================

  'denali': [
    {
      id: 'savage-river-loop',
      name: 'Savage River Loop',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Easy loop with mountain views and wildlife.',
      trailhead: [-149.3200, 63.7200],
      isLoop: true,
    },
    {
      id: 'horseshoe-lake-trail',
      name: 'Horseshoe Lake Trail',
      distance: 3.2,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Lake views with beaver activity and taiga forest.',
      trailhead: [-149.3050, 63.7350],
    },
    {
      id: 'mount-healy-overlook',
      name: 'Mount Healy Overlook Trail',
      distance: 5.0,
      difficulty: 'strenuous',
      elevationGain: 1700,
      description: 'Panoramic views of Denali and Alaska Range.',
      trailhead: [-149.2850, 63.7200],
    },
    {
      id: 'eielson-alpine-trail',
      name: 'Eielson Alpine Trail',
      distance: 1.0,
      difficulty: 'moderate',
      elevationGain: 350,
      description: 'Short but steep climb from Eielson Visitor Center.',
      trailhead: [-150.2900, 63.4350],
    },
    {
      id: 'wonder-lake-hike',
      name: 'Wonder Lake Area',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Classic Denali reflection views from lake shores.',
      trailhead: [-150.8700, 63.4600],
    },
  ],

  'gates-of-the-arctic': [
    {
      id: 'arrigetch-peaks-approach',
      name: 'Arrigetch Peaks Approach',
      distance: 12.0,
      difficulty: 'strenuous',
      elevationGain: 2000,
      description: 'Challenging route to dramatic granite spires.',
      trailhead: [-154.2000, 67.4200],
    },
    {
      id: 'arctic-interagency-visitor',
      name: 'Arctic Interagency Visitor Center Walk',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Interpretive trails near Coldfoot.',
      trailhead: [-150.1800, 67.2500],
    },
    {
      id: 'north-fork-koyukuk',
      name: 'North Fork Koyukuk Valley',
      distance: 15.0,
      difficulty: 'strenuous',
      elevationGain: 1500,
      description: 'Remote wilderness river valley route.',
      trailhead: [-150.5000, 67.5000],
    },
    {
      id: 'boreal-forest-walk',
      name: 'Boreal Forest Walk (Bettles)',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Accessible area near park gateway community.',
      trailhead: [-151.5200, 66.9200],
    },
    {
      id: 'brooks-range-traverse',
      name: 'Brooks Range Traverse',
      distance: 25.0,
      difficulty: 'strenuous',
      elevationGain: 4000,
      description: 'Multi-day expedition through Arctic wilderness.',
      trailhead: [-152.0000, 67.8000],
    },
  ],

  'glacier-bay': [
    {
      id: 'bartlett-river-trail',
      name: 'Bartlett River Trail',
      distance: 4.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Rainforest trail to river estuary.',
      trailhead: [-135.8850, 58.4550],
    },
    {
      id: 'forest-loop-trail',
      name: 'Forest Loop Trail',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Interpretive trail through coastal rainforest.',
      trailhead: [-135.8800, 58.4500],
      isLoop: true,
    },
    {
      id: 'point-gustavus-beach',
      name: 'Point Gustavus Beach Walk',
      distance: 6.0,
      difficulty: 'moderate',
      elevationGain: 50,
      description: 'Coastal beach walk with whale watching.',
      trailhead: [-135.9100, 58.3900],
    },
    {
      id: 'bartlett-cove-tidal',
      name: 'Bartlett Cove Tidal Flats',
      distance: 2.5,
      difficulty: 'easy',
      elevationGain: 20,
      description: 'Explore intertidal zone at low tide.',
      trailhead: [-135.8800, 58.4550],
    },
    {
      id: 'beartrack-cove-trail',
      name: 'Beartrack Cove Trail',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Secluded cove with bear activity.',
      trailhead: [-135.8900, 58.4600],
    },
  ],

  'katmai': [
    {
      id: 'brooks-falls-trail',
      name: 'Brooks Falls Trail',
      distance: 1.2,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Famous bear-viewing platform at the falls.',
      trailhead: [-155.7800, 58.5550],
    },
    {
      id: 'valley-of-ten-thousand-smokes',
      name: 'Valley of Ten Thousand Smokes',
      distance: 12.0,
      difficulty: 'strenuous',
      elevationGain: 1000,
      description: 'Volcanic ash landscape from 1912 eruption.',
      trailhead: [-155.3500, 58.3500],
    },
    {
      id: 'dumpling-mountain-trail',
      name: 'Dumpling Mountain Trail',
      distance: 4.0,
      difficulty: 'strenuous',
      elevationGain: 2400,
      description: 'Panoramic views of Naknek Lake.',
      trailhead: [-155.7800, 58.5500],
    },
    {
      id: 'brooks-camp-cultural',
      name: 'Brooks Camp Cultural Walk',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 20,
      description: 'Interpretive trail with archaeological sites.',
      trailhead: [-155.7800, 58.5550],
    },
    {
      id: 'ukak-falls-route',
      name: 'Ukak Falls Route',
      distance: 6.0,
      difficulty: 'strenuous',
      elevationGain: 800,
      description: 'Remote waterfall in volcanic landscape.',
      trailhead: [-155.3000, 58.3000],
    },
  ],

  'kenai-fjords': [
    {
      id: 'exit-glacier-trail',
      name: 'Exit Glacier Trail',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Walk to face of retreating glacier.',
      trailhead: [-149.6700, 60.1850],
    },
    {
      id: 'harding-icefield-trail',
      name: 'Harding Icefield Trail',
      distance: 8.2,
      difficulty: 'strenuous',
      elevationGain: 3500,
      description: 'Stunning views of 300-square-mile icefield.',
      trailhead: [-149.6700, 60.1850],
    },
    {
      id: 'glacier-view-loop',
      name: 'Glacier View Loop',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Accessible boardwalk with glacier overlooks.',
      trailhead: [-149.6700, 60.1850],
      isLoop: true,
    },
    {
      id: 'toe-of-glacier-loop',
      name: 'Toe of the Glacier Loop',
      distance: 0.6,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Closest approach to glacier terminus.',
      trailhead: [-149.6700, 60.1850],
      isLoop: true,
    },
    {
      id: 'nature-center-trail',
      name: 'Nature Center Trail',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 30,
      description: 'Short interpretive walk from visitor center.',
      trailhead: [-149.6700, 60.1900],
    },
  ],

  'kobuk-valley': [
    {
      id: 'great-kobuk-sand-dunes',
      name: 'Great Kobuk Sand Dunes',
      distance: 5.0,
      difficulty: 'strenuous',
      elevationGain: 500,
      description: 'Arctic sand dunes reaching 100 feet high.',
      trailhead: [-158.9700, 66.8850],
    },
    {
      id: 'little-kobuk-sand-dunes',
      name: 'Little Kobuk Sand Dunes',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Smaller but accessible dune field.',
      trailhead: [-159.1000, 66.9200],
    },
    {
      id: 'salmon-river-route',
      name: 'Salmon River Route',
      distance: 8.0,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'River valley hiking with wildlife.',
      trailhead: [-159.2000, 66.8500],
    },
    {
      id: 'hunt-river-hills',
      name: 'Hunt River Hills',
      distance: 6.0,
      difficulty: 'strenuous',
      elevationGain: 1200,
      description: 'Rolling tundra with panoramic views.',
      trailhead: [-159.0000, 66.9500],
    },
    {
      id: 'onion-portage-archaeological',
      name: 'Onion Portage Archaeological Site',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Historic caribou crossing with cultural significance.',
      trailhead: [-158.8500, 66.9100],
    },
  ],

  'lake-clark': [
    {
      id: 'tanalian-falls-trail',
      name: 'Tanalian Falls Trail',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Waterfall and mountain views near Port Alsworth.',
      trailhead: [-154.3200, 60.2050],
    },
    {
      id: 'tanalian-mountain-trail',
      name: 'Tanalian Mountain Trail',
      distance: 6.5,
      difficulty: 'strenuous',
      elevationGain: 3400,
      description: 'Summit with panoramic lake and volcano views.',
      trailhead: [-154.3200, 60.2050],
    },
    {
      id: 'kontrashibuna-lake-route',
      name: 'Kontrashibuna Lake Route',
      distance: 5.0,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Scenic lake accessed from Port Alsworth.',
      trailhead: [-154.3500, 60.2200],
    },
    {
      id: 'beaver-pond-loop',
      name: 'Beaver Pond Loop',
      distance: 1.5,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Wildlife viewing near town.',
      trailhead: [-154.3100, 60.2000],
      isLoop: true,
    },
    {
      id: 'telaquana-lake-approach',
      name: 'Telaquana Lake Approach',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 1500,
      description: 'Remote wilderness lake route.',
      trailhead: [-154.5000, 60.4000],
    },
  ],

  'wrangell-st-elias': [
    {
      id: 'root-glacier-trail',
      name: 'Root Glacier Trail',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Walk onto glacier from historic Kennecott.',
      trailhead: [-142.8850, 61.4850],
    },
    {
      id: 'bonanza-mine-trail',
      name: 'Bonanza Mine Trail',
      distance: 9.0,
      difficulty: 'strenuous',
      elevationGain: 3800,
      description: 'Historic copper mine with stunning views.',
      trailhead: [-142.8830, 61.4870],
    },
    {
      id: 'erie-mine-trail',
      name: 'Erie Mine Trail',
      distance: 6.0,
      difficulty: 'strenuous',
      elevationGain: 2500,
      description: 'Mining ruins above Kennecott townsite.',
      trailhead: [-142.8900, 61.4900],
    },
    {
      id: 'jumbo-mine-trail',
      name: 'Jumbo Mine Trail',
      distance: 4.5,
      difficulty: 'moderate',
      elevationGain: 1200,
      description: 'Well-preserved historic mine structures.',
      trailhead: [-142.8800, 61.4800],
    },
    {
      id: 'nabesna-road-trails',
      name: 'Nabesna Road Trails',
      distance: 8.0,
      difficulty: 'moderate',
      elevationGain: 1000,
      description: 'Accessible trails from park road corridor.',
      trailhead: [-143.0500, 62.4000],
    },
  ],

  // ==========================================
  // PHASE 3B: CALIFORNIA PARKS (3 Parks)
  // ==========================================

  'channel-islands': [
    {
      id: 'cavern-point-loop',
      name: 'Cavern Point Loop',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 300,
      description: 'Dramatic sea cliffs on Santa Cruz Island.',
      trailhead: [-119.5550, 34.0500],
    },
    {
      id: 'scorpion-canyon-loop',
      name: 'Scorpion Canyon Loop',
      distance: 4.5,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Historic ranch and canyon exploration.',
      trailhead: [-119.5500, 34.0470],
    },
    {
      id: 'prisoners-harbor-to-pelican-bay',
      name: 'Prisoners Harbor to Pelican Bay',
      distance: 7.0,
      difficulty: 'moderate',
      elevationGain: 800,
      description: 'Coastal traverse with endemic plant life.',
      trailhead: [-119.6850, 34.0200],
    },
    {
      id: 'inspiration-point-trail',
      name: 'Inspiration Point Trail',
      distance: 2.8,
      difficulty: 'moderate',
      elevationGain: 500,
      description: 'Sweeping views of Anacapa Island.',
      trailhead: [-119.4350, 34.0150],
    },
    {
      id: 'water-canyon-trail',
      name: 'Water Canyon Trail',
      distance: 4.0,
      difficulty: 'moderate',
      elevationGain: 700,
      description: 'Beach access on Santa Rosa Island.',
      trailhead: [-120.1000, 33.9600],
    },
  ],

  'kings-canyon': [
    {
      id: 'mist-falls-trail',
      name: 'Mist Falls Trail',
      distance: 8.4,
      difficulty: 'moderate',
      elevationGain: 800,
      description: 'One of the largest waterfalls in the park.',
      trailhead: [-118.5550, 36.7960],
    },
    {
      id: 'zumwalt-meadow-loop',
      name: 'Zumwalt Meadow Loop',
      distance: 1.5,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Lush meadow beneath towering granite walls.',
      trailhead: [-118.5700, 36.7800],
    },
    {
      id: 'big-stump-loop',
      name: 'Big Stump Loop',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Historic logging area with massive stumps.',
      trailhead: [-118.9650, 36.7500],
    },
    {
      id: 'roaring-river-falls',
      name: 'Roaring River Falls',
      distance: 0.4,
      difficulty: 'easy',
      elevationGain: 30,
      description: 'Short walk to powerful cascade.',
      trailhead: [-118.5850, 36.7750],
    },
    {
      id: 'general-grant-tree-trail',
      name: 'General Grant Tree Trail',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Third-largest tree in the world.',
      trailhead: [-118.9700, 36.7460],
    },
  ],

  'pinnacles': [
    {
      id: 'high-peaks-loop',
      name: 'High Peaks Loop',
      distance: 6.7,
      difficulty: 'strenuous',
      elevationGain: 1300,
      description: 'Dramatic volcanic spires with condor sightings.',
      trailhead: [-121.1880, 36.4850],
    },
    {
      id: 'bear-gulch-cave-trail',
      name: 'Bear Gulch Cave Trail',
      distance: 2.2,
      difficulty: 'moderate',
      elevationGain: 350,
      description: 'Talus caves with seasonal bat colonies.',
      trailhead: [-121.1850, 36.4800],
    },
    {
      id: 'balconies-cave-trail',
      name: 'Balconies Cave Trail',
      distance: 2.4,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Explore dramatic talus cave system.',
      trailhead: [-121.2150, 36.4900],
    },
    {
      id: 'condor-gulch-trail',
      name: 'Condor Gulch Trail',
      distance: 5.3,
      difficulty: 'strenuous',
      elevationGain: 1100,
      description: 'Prime California condor viewing area.',
      trailhead: [-121.1870, 36.4860],
    },
    {
      id: 'bench-trail',
      name: 'Bench Trail',
      distance: 5.4,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Connecting trail with wildflower displays.',
      trailhead: [-121.1900, 36.4820],
    },
  ],

  // ==========================================
  // PHASE 3C: WESTERN PARKS (6 Parks)
  // ==========================================

  'black-canyon': [
    {
      id: 'rim-rock-nature-trail',
      name: 'Rim Rock Nature Trail',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Canyon rim views with interpretive signs.',
      trailhead: [-107.7250, 38.5750],
    },
    {
      id: 'oak-flat-loop',
      name: 'Oak Flat Loop',
      distance: 2.0,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Descend to Gambel oak grove on canyon wall.',
      trailhead: [-107.7300, 38.5700],
    },
    {
      id: 'warner-point-nature-trail',
      name: 'Warner Point Nature Trail',
      distance: 1.5,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Highest viewpoint on South Rim at 8,300 ft.',
      trailhead: [-107.6850, 38.5500],
    },
    {
      id: 'north-vista-trail',
      name: 'North Vista Trail',
      distance: 7.0,
      difficulty: 'strenuous',
      elevationGain: 1100,
      description: 'Hike to Green Mountain overlook.',
      trailhead: [-107.7100, 38.5950],
    },
    {
      id: 'gunnison-route',
      name: 'Gunnison Route',
      distance: 1.8,
      difficulty: 'strenuous',
      elevationGain: 1800,
      description: 'Steep descent to river, chains required.',
      trailhead: [-107.7200, 38.5650],
    },
  ],

  'great-sand-dunes': [
    {
      id: 'high-dune-route',
      name: 'High Dune Route',
      distance: 2.5,
      difficulty: 'strenuous',
      elevationGain: 699,
      description: 'First major ridge with panoramic views.',
      trailhead: [-105.5150, 37.7330],
    },
    {
      id: 'star-dune-route',
      name: 'Star Dune Route',
      distance: 6.5,
      difficulty: 'strenuous',
      elevationGain: 750,
      description: 'Tallest dune in North America at 755 ft.',
      trailhead: [-105.5150, 37.7330],
    },
    {
      id: 'mosca-pass-trail',
      name: 'Mosca Pass Trail',
      distance: 7.0,
      difficulty: 'moderate',
      elevationGain: 1500,
      description: 'Historic route through montane forest.',
      trailhead: [-105.5200, 37.7200],
    },
    {
      id: 'medano-lake-trail',
      name: 'Medano Lake Trail',
      distance: 11.0,
      difficulty: 'strenuous',
      elevationGain: 2600,
      description: 'Alpine lake beneath rugged peaks.',
      trailhead: [-105.5100, 37.7400],
    },
    {
      id: 'dunes-overlook-trail',
      name: 'Dunes Overlook Trail',
      distance: 2.3,
      difficulty: 'moderate',
      elevationGain: 350,
      description: 'Forest walk with dune field panorama.',
      trailhead: [-105.5300, 37.7250],
    },
  ],

  'great-basin': [
    {
      id: 'bristlecone-pine-trail',
      name: 'Bristlecone Pine Trail',
      distance: 2.8,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Ancient trees over 4,000 years old.',
      trailhead: [-114.2180, 38.9850],
    },
    {
      id: 'wheeler-peak-summit-trail',
      name: 'Wheeler Peak Summit Trail',
      distance: 8.6,
      difficulty: 'strenuous',
      elevationGain: 2900,
      description: 'Nevada\'s second-highest peak at 13,063 ft.',
      trailhead: [-114.2200, 38.9900],
    },
    {
      id: 'alpine-lakes-loop',
      name: 'Alpine Lakes Loop',
      distance: 2.7,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Stella and Teresa lakes beneath Wheeler Peak.',
      trailhead: [-114.2180, 38.9870],
    },
    {
      id: 'lehman-creek-trail',
      name: 'Lehman Creek Trail',
      distance: 6.8,
      difficulty: 'moderate',
      elevationGain: 2050,
      description: 'Connector from visitor center to Wheeler Peak.',
      trailhead: [-114.2200, 39.0050],
    },
    {
      id: 'mountain-view-nature-trail',
      name: 'Mountain View Nature Trail',
      distance: 0.3,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Short loop near Lehman Caves entrance.',
      trailhead: [-114.2200, 39.0050],
    },
  ],

  'petrified-forest': [
    {
      id: 'blue-mesa-trail',
      name: 'Blue Mesa Trail',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Blue-striped badlands with petrified logs.',
      trailhead: [-109.7870, 34.9350],
    },
    {
      id: 'crystal-forest-trail',
      name: 'Crystal Forest Trail',
      distance: 0.75,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Dense concentration of colorful petrified wood.',
      trailhead: [-109.8000, 34.8600],
    },
    {
      id: 'giant-logs-trail',
      name: 'Giant Logs Trail',
      distance: 0.4,
      difficulty: 'easy',
      elevationGain: 30,
      description: 'Largest petrified logs in the park.',
      trailhead: [-109.7850, 34.8150],
    },
    {
      id: 'painted-desert-rim-trail',
      name: 'Painted Desert Rim Trail',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Colorful badlands views at north entrance.',
      trailhead: [-109.7800, 35.0650],
    },
    {
      id: 'puerco-pueblo-trail',
      name: 'Puerco Pueblo Trail',
      distance: 0.3,
      difficulty: 'easy',
      elevationGain: 20,
      description: 'Ancestral Puebloan ruins and petroglyphs.',
      trailhead: [-109.7900, 34.9700],
    },
  ],

  'saguaro': [
    {
      id: 'valley-view-overlook-trail',
      name: 'Valley View Overlook Trail',
      distance: 0.8,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Scenic desert views with saguaro forest.',
      trailhead: [-110.7380, 32.1850],
    },
    {
      id: 'signal-hill-trail',
      name: 'Signal Hill Trail',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Ancient Hohokam petroglyphs on boulders.',
      trailhead: [-111.2100, 32.2550],
    },
    {
      id: 'douglas-spring-trail',
      name: 'Douglas Spring Trail',
      distance: 12.0,
      difficulty: 'strenuous',
      elevationGain: 2200,
      description: 'Rincon Mountain wilderness access.',
      trailhead: [-110.6950, 32.1750],
    },
    {
      id: 'mica-view-loop',
      name: 'Mica View Loop',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Accessible loop through saguaro forest.',
      trailhead: [-110.7350, 32.1700],
    },
    {
      id: 'wasson-peak-trail',
      name: 'Wasson Peak Trail',
      distance: 8.0,
      difficulty: 'strenuous',
      elevationGain: 1800,
      description: 'Highest point in Tucson Mountain District.',
      trailhead: [-111.2000, 32.2400],
    },
  ],

  'white-sands': [
    {
      id: 'dune-life-nature-trail',
      name: 'Dune Life Nature Trail',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Interpretive trail about desert adaptations.',
      trailhead: [-106.1750, 32.7850],
      isLoop: true,
    },
    {
      id: 'interdune-boardwalk',
      name: 'Interdune Boardwalk',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 20,
      description: 'Accessible boardwalk into dune field.',
      trailhead: [-106.1800, 32.7800],
    },
    {
      id: 'alkali-flat-trail',
      name: 'Alkali Flat Trail',
      distance: 5.0,
      difficulty: 'strenuous',
      elevationGain: 200,
      description: 'Challenging loop through heart of dunes.',
      trailhead: [-106.2100, 32.7700],
      isLoop: true,
    },
    {
      id: 'backcountry-camping-loop',
      name: 'Backcountry Camping Loop',
      distance: 2.0,
      difficulty: 'moderate',
      elevationGain: 100,
      description: 'Access to primitive camping among dunes.',
      trailhead: [-106.2000, 32.7750],
      isLoop: true,
    },
    {
      id: 'playa-trail',
      name: 'Playa Trail',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 10,
      description: 'Walk to dry lake bed at dune edge.',
      trailhead: [-106.1700, 32.7900],
    },
  ],

  // ==========================================
  // PHASE 3D: REMAINING PARKS (6 Parks)
  // ==========================================

  'capitol-reef': [
    {
      id: 'hickman-bridge-trail',
      name: 'Hickman Bridge Trail',
      distance: 1.8,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Natural 133-foot sandstone bridge.',
      trailhead: [-111.2420, 38.2880],
    },
    {
      id: 'cassidy-arch-trail',
      name: 'Cassidy Arch Trail',
      distance: 3.4,
      difficulty: 'strenuous',
      elevationGain: 900,
      description: 'Named for outlaw Butch Cassidy. Views of Grand Wash.',
      trailhead: [-111.1650, 38.2600],
    },
    {
      id: 'grand-wash-trail',
      name: 'Grand Wash Trail',
      distance: 4.4,
      difficulty: 'easy',
      elevationGain: 200,
      description: 'Narrow slot canyon with towering walls.',
      trailhead: [-111.1650, 38.2600],
    },
    {
      id: 'capitol-gorge-trail',
      name: 'Capitol Gorge Trail',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Pioneer inscriptions and water pockets.',
      trailhead: [-111.1400, 38.2250],
    },
    {
      id: 'cohab-canyon-trail',
      name: 'Cohab Canyon Trail',
      distance: 3.5,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Hidden canyon with overlooks of Fruita.',
      trailhead: [-111.2450, 38.2850],
    },
  ],

  'canyonlands': [
    {
      id: 'mesa-arch-trail',
      name: 'Mesa Arch Trail',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 80,
      description: 'Famous sunrise photo spot overlooking canyon.',
      trailhead: [-109.8650, 38.3890],
    },
    {
      id: 'grand-view-point-trail',
      name: 'Grand View Point Trail',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Panoramic views of canyon country.',
      trailhead: [-109.8580, 38.3100],
    },
    {
      id: 'upheaval-dome-trail',
      name: 'Upheaval Dome Overlook',
      distance: 1.8,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Mysterious geological formation, meteor vs salt dome.',
      trailhead: [-109.9280, 38.4250],
    },
    {
      id: 'druid-arch-trail',
      name: 'Druid Arch Trail',
      distance: 11.0,
      difficulty: 'strenuous',
      elevationGain: 1400,
      description: 'Needles District highlight. Ladder climbing required.',
      trailhead: [-109.8000, 38.1500],
    },
    {
      id: 'chesler-park-loop',
      name: 'Chesler Park Loop',
      distance: 11.0,
      difficulty: 'strenuous',
      elevationGain: 1000,
      description: 'Desert grassland surrounded by colorful spires.',
      trailhead: [-109.8000, 38.1500],
      isLoop: true,
    },
  ],

  'new-river-gorge': [
    {
      id: 'long-point-trail',
      name: 'Long Point Trail',
      distance: 3.2,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Best view of New River Gorge Bridge.',
      trailhead: [-81.0750, 38.0700],
    },
    {
      id: 'endless-wall-trail',
      name: 'Endless Wall Trail',
      distance: 2.4,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Rim walk with rock climbing views.',
      trailhead: [-81.0600, 38.0650],
    },
    {
      id: 'kaymoor-miners-trail',
      name: 'Kaymoor Miners Trail',
      distance: 2.0,
      difficulty: 'strenuous',
      elevationGain: 700,
      description: '821 steps to historic coal mining area.',
      trailhead: [-81.0800, 38.0550],
    },
    {
      id: 'grandview-rim-trail',
      name: 'Grandview Rim Trail',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Multiple overlooks on canyon rim.',
      trailhead: [-81.0500, 37.8250],
      isLoop: true,
    },
    {
      id: 'nuttallburg-trail',
      name: 'Nuttallburg Trail',
      distance: 2.0,
      difficulty: 'moderate',
      elevationGain: 500,
      description: 'Ghost town and industrial ruins.',
      trailhead: [-81.0350, 38.0400],
    },
  ],

  'indiana-dunes': [
    {
      id: 'west-beach-dune-succession',
      name: 'Dune Succession Trail',
      distance: 1.0,
      difficulty: 'moderate',
      elevationGain: 100,
      description: 'Learn dune ecology with beach access.',
      trailhead: [-87.2100, 41.6200],
      isLoop: true,
    },
    {
      id: 'cowles-bog-trail',
      name: 'Cowles Bog Trail',
      distance: 4.7,
      difficulty: 'moderate',
      elevationGain: 200,
      description: 'Rare wetland habitat to Lake Michigan.',
      trailhead: [-87.0900, 41.6350],
    },
    {
      id: 'mount-baldy-trail',
      name: 'Mount Baldy Trail',
      distance: 1.5,
      difficulty: 'moderate',
      elevationGain: 126,
      description: 'Highest dune with lake views. Guided only.',
      trailhead: [-86.9100, 41.7050],
      isLoop: true,
    },
    {
      id: 'pinhook-bog-trail',
      name: 'Pinhook Bog Trail',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 30,
      description: 'Quaking bog with carnivorous plants. Ranger-led.',
      trailhead: [-86.8350, 41.6150],
      isLoop: true,
    },
    {
      id: 'bailly-chellberg-trails',
      name: 'Bailly/Chellberg Trails',
      distance: 3.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Historic homesteads and cemetery.',
      trailhead: [-87.0800, 41.6150],
      isLoop: true,
    },
  ],

  'american-samoa': [
    {
      id: 'mount-alava-trail',
      name: 'Mount Alava Trail',
      distance: 7.0,
      difficulty: 'strenuous',
      elevationGain: 1600,
      description: 'Summit ridge with harbor and rainforest views.',
      trailhead: [-170.6900, -14.2700],
    },
    {
      id: 'tuafanua-trail',
      name: 'Tuafanua Trail',
      distance: 3.0,
      difficulty: 'moderate',
      elevationGain: 500,
      description: 'Coastal walk through traditional villages.',
      trailhead: [-170.6800, -14.2650],
    },
    {
      id: 'pola-island-trail',
      name: 'Pola Island Trail',
      distance: 1.5,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Rocky islet with seabird colonies.',
      trailhead: [-170.6000, -14.2550],
    },
    {
      id: 'ofu-beach-loop',
      name: 'Ofu Beach Loop',
      distance: 2.0,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Pristine coral reef and palm-fringed beach.',
      trailhead: [-169.6750, -14.1800],
    },
    {
      id: 'amalau-valley-rainforest',
      name: 'Amalau Valley Rainforest Trail',
      distance: 4.0,
      difficulty: 'strenuous',
      elevationGain: 800,
      description: 'Dense tropical forest with flying foxes.',
      trailhead: [-170.6850, -14.2600],
    },
  ],

  'gateway-arch': [
    {
      id: 'riverfront-trail',
      name: 'Riverfront Trail',
      distance: 2.5,
      difficulty: 'easy',
      elevationGain: 20,
      description: 'Mississippi River walk with Arch views.',
      trailhead: [-90.1850, 38.6240],
    },
    {
      id: 'old-courthouse-walk',
      name: 'Old Courthouse Walk',
      distance: 0.3,
      difficulty: 'easy',
      elevationGain: 10,
      description: 'Historic courthouse with Dred Scott exhibits.',
      trailhead: [-90.1890, 38.6260],
    },
    {
      id: 'arch-grounds-loop',
      name: 'Arch Grounds Loop',
      distance: 1.5,
      difficulty: 'easy',
      elevationGain: 30,
      description: 'Circle the iconic stainless steel arch.',
      trailhead: [-90.1850, 38.6250],
    },
    {
      id: 'luther-ely-smith-square',
      name: 'Luther Ely Smith Square',
      distance: 0.2,
      difficulty: 'easy',
      elevationGain: 0,
      description: 'Park entrance with fountains and gardens.',
      trailhead: [-90.1870, 38.6265],
    },
    {
      id: 'north-gateway-walk',
      name: 'North Gateway Walk',
      distance: 0.5,
      difficulty: 'easy',
      elevationGain: 10,
      description: 'Connection to Laclede\'s Landing.',
      trailhead: [-90.1840, 38.6280],
    },
  ],

  'north-cascades': [
    {
      id: 'cascade-pass-trail',
      name: 'Cascade Pass Trail',
      distance: 7.4,
      difficulty: 'strenuous',
      elevationGain: 1800,
      description: 'Iconic alpine pass with glacier views.',
      trailhead: [-121.0750, 48.4750],
    },
    {
      id: 'thunder-knob-trail',
      name: 'Thunder Knob Trail',
      distance: 3.6,
      difficulty: 'moderate',
      elevationGain: 500,
      description: 'Diablo Lake panorama from forested knob.',
      trailhead: [-121.1100, 48.7100],
    },
    {
      id: 'diablo-lake-trail',
      name: 'Diablo Lake Trail',
      distance: 7.6,
      difficulty: 'strenuous',
      elevationGain: 1400,
      description: 'Turquoise glacial lake loop.',
      trailhead: [-121.1150, 48.7150],
    },
    {
      id: 'maple-pass-loop',
      name: 'Maple Pass Loop',
      distance: 7.2,
      difficulty: 'strenuous',
      elevationGain: 2150,
      description: 'Premier fall foliage with lake views.',
      trailhead: [-120.7350, 48.5200],
    },
    {
      id: 'ross-dam-trail',
      name: 'Ross Dam Trail',
      distance: 1.0,
      difficulty: 'moderate',
      elevationGain: 600,
      description: 'Steep descent to massive hydroelectric dam.',
      trailhead: [-121.0650, 48.7300],
    },
  ],

  'virgin-islands': [
    {
      id: 'trunk-bay-trail',
      name: 'Trunk Bay Trail',
      distance: 0.75,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'World-famous beach with underwater snorkel trail.',
      trailhead: [-64.7700, 18.3530],
    },
    {
      id: 'reef-bay-trail',
      name: 'Reef Bay Trail',
      distance: 5.2,
      difficulty: 'moderate',
      elevationGain: 1000,
      description: 'Petroglyphs, sugar ruins, and beach access.',
      trailhead: [-64.7350, 18.3300],
    },
    {
      id: 'ram-head-trail',
      name: 'Ram Head Trail',
      distance: 1.9,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Dramatic headland with Caribbean views.',
      trailhead: [-64.7200, 18.3100],
    },
    {
      id: 'lind-point-trail',
      name: 'Lind Point Trail',
      distance: 2.2,
      difficulty: 'moderate',
      elevationGain: 250,
      description: 'Connects Cruz Bay to Honeymoon Beach.',
      trailhead: [-64.7930, 18.3320],
    },
    {
      id: 'cinnamon-bay-nature-loop',
      name: 'Cinnamon Bay Nature Loop',
      distance: 1.0,
      difficulty: 'easy',
      elevationGain: 100,
      description: 'Sugar plantation ruins and tropical forest.',
      trailhead: [-64.7530, 18.3550],
    },
  ],

  'wind-cave': [
    {
      id: 'natural-entrance-trail',
      name: 'Natural Entrance Trail',
      distance: 0.3,
      difficulty: 'easy',
      elevationGain: 50,
      description: 'Historic cave entrance with breathing wind.',
      trailhead: [-103.4800, 43.5570],
    },
    {
      id: 'rankin-ridge-trail',
      name: 'Rankin Ridge Trail',
      distance: 1.25,
      difficulty: 'moderate',
      elevationGain: 300,
      description: 'Highest point in park with fire tower.',
      trailhead: [-103.4250, 43.5200],
    },
    {
      id: 'cold-brook-canyon-trail',
      name: 'Cold Brook Canyon Trail',
      distance: 2.8,
      difficulty: 'moderate',
      elevationGain: 400,
      description: 'Prairie and ponderosa pine forest.',
      trailhead: [-103.4780, 43.5550],
    },
    {
      id: 'centennial-trail-wind-cave',
      name: 'Centennial Trail (Wind Cave Section)',
      distance: 6.0,
      difficulty: 'strenuous',
      elevationGain: 600,
      description: 'Long-distance trail crossing mixed-grass prairie.',
      trailhead: [-103.4300, 43.5100],
    },
    {
      id: 'elk-mountain-trail',
      name: 'Elk Mountain Trail',
      distance: 3.5,
      difficulty: 'moderate',
      elevationGain: 450,
      description: 'Wildlife viewing with bison and elk.',
      trailhead: [-103.4700, 43.5400],
    },
  ],
};

// Helper function to get trails for a specific park
export function getTrailsForPark(parkId: string): Trail[] {
  return PARK_TRAILS[parkId] || [];
}

// Helper function to get difficulty label with proper casing
export function getDifficultyLabel(difficulty: TrailDifficulty): string {
  return difficulty.charAt(0).toUpperCase() + difficulty.slice(1);
}
