project_id = "pgaduiukijwoenibybvq"

[functions.google-places-autocomplete]
verify_jwt = false

[functions.google-places-details]
verify_jwt = false

[functions.google-places-photo]
verify_jwt = false

[functions.discover-events]
verify_jwt = false

[functions.google-places-nearby]
verify_jwt = false

[functions.seed-city-places]
verify_jwt = false

[functions.refresh-places]
verify_jwt = false

[functions.compute-place-taxonomy]
verify_jwt = false

[functions.store-place-photos]
verify_jwt = false
