project_id = "pgaduiukijwoenibybvq"

[functions.send-invite]
verify_jwt = false

[functions.validate-invite]
verify_jwt = false

[functions.generate-couple-profile]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.google-places-details]
verify_jwt = false
